from app.config import settings
from app.agent.tools import (
    TOOL_QUERY_INVENTORY,
    TOOL_INITIATE_MOMO_PAYMENT,
    TOOL_CHECK_ORDER_STATUS,
    TOOL_GET_BUSINESS_HOURS,
    TOOL_GET_REVENUE_SUMMARY,
    TOOL_GET_TOP_PRODUCTS,
    TOOL_LIST_PENDING_ORDERS,
    TOOL_UPDATE_INVENTORY,
    TOOL_GET_FAILED_PAYMENTS,
    TOOL_GET_CUSTOMER_HISTORY,
    TOOL_SEND_BROADCAST,
)

CUSTOMER_TOOLS = [
    TOOL_QUERY_INVENTORY,
    TOOL_INITIATE_MOMO_PAYMENT,
    TOOL_CHECK_ORDER_STATUS,
    TOOL_GET_BUSINESS_HOURS,
]

MERCHANT_TOOLS = CUSTOMER_TOOLS + [
    TOOL_GET_REVENUE_SUMMARY,
    TOOL_GET_TOP_PRODUCTS,
    TOOL_LIST_PENDING_ORDERS,
    TOOL_UPDATE_INVENTORY,
    TOOL_GET_FAILED_PAYMENTS,
    TOOL_GET_CUSTOMER_HISTORY,
    TOOL_SEND_BROADCAST,
]


def get_tools(phone: str) -> list:
    if phone == settings.MERCHANT_PHONE:
        return MERCHANT_TOOLS
    return CUSTOMER_TOOLS


def is_merchant(phone: str) -> bool:
    return phone == settings.MERCHANT_PHONE
